backend:
  name: github
  repo: janak1981/Janak
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "writing"
    label: "Writing & Research"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
